### ISSUE TITLE
Activity buttons badly spaced (Pause/Resume/Finish and submit)

### ISSUE THREAD

**Issue by gaidheal1** [gaidheal1/progression#17]
Edit CSS file

**Comment by Noorain464** [comment]
Hello I would like to work on this issue

**Comment by gaidheal1** [comment]
Hey @Noorain464 that's awesome, you're my first contributor! Thanks so much for offering. Do you need me to do anything, like create a branch? If not, I guess you can branch off origin (bootstrap2) directly.

**Comment by Noorain464** [comment]
Can you give some guidelines on how to setup or if it there where can I  find it? and also 
Can you provide me with some screenshots??

**Comment by gaidheal1** [comment]
Forgive me, I'm not sure what you're asking for: what setup do you need help with, and screenshots of what? 
I can see you've already forked the repository, and that you've made a few GitHub contributions already, but I don't know how confident you are using GitHub. I'm still getting used to it myself ;)

**Comment by gaidheal1** [comment]
I can see it would help to provide screenshots; I'll do that in a bit. If you haven't found it already, [the site is deployed here](https://gaidheal1.github.io/progression)

**Comment by Noorain464** [comment]
I have figured it out and I have requested for pull.
Please verify.
Thank you.

**Comment by gaidheal1** [comment]
Nice, I'll have a look. 
Just adding screenshot for the record, and to get into the habit!
![progression activity buttons spacing](https://github.com/user-attachments/assets/b0677311-ca59-41bf-99e4-9a4d5fc68b32)
